Repository aws-educate-tw/aws-educate-tpet-backend, pull requests merged in 2024-07, with the labels that each got.

#27 [SCRUM-71] Fix and Refactor - Upload Multiple Files with URL Encoding
  src/email_service/send_email/ses.py
  src/file_service/upload_multiple_file/Dockerfile
  src/file_service/upload_multiple_file/dynamodb.py
  src/file_service/upload_multiple_file/lambda_function.py
  src/file_service/upload_multiple_file/time_util.py
Labels: bug

#37 [SCRUM-97] Login api CORS error
  src/auth_service/is_logged_in/Dockerfile
  src/auth_service/is_logged_in/lambda_function.py
  src/auth_service/is_logged_in/requirements.txt
  src/auth_service/login/lambda_function.py
  src/auth_service/terraform/api_gateway.tf
  src/auth_service/terraform/lambda.tf
Labels: bug

#38 [SCRUM-97] Login api CORS origin not allowed error
  src/auth_service/login/lambda_function.py
Labels: bug

#41 [SCRUM-104] Enabled CloudFront standard logging for debugging
  terraform/cloudfront_for_apis/.terraform.lock.hcl
  terraform/cloudfront_for_apis/cloudfront.tf
  terraform/cloudfront_for_apis/s3.tf
Labels: bug, enhancement

#42 SCRUM-55--lastEvaluated-Key
  src/file_service/list_files/Dockerfile
  src/file_service/list_files/file_repository.py
  src/file_service/list_files/file_service_pagination_state_repository.py
  src/file_service/list_files/lambda_function.py
  src/file_service/list_files/requirements.txt
  src/file_service/list_files/time_util.py
  src/file_service/terraform/.terraform.lock.hcl
  src/file_service/terraform/api_gateway.tf
  src/file_service/terraform/dynamodb.tf
  src/file_service/terraform/lambda.tf
Labels: feature

#43 [SCRUM-105] List files - 500 error none type object is not subscriptable
  src/auth_service/is_logged_in/lambda_function.py
  src/auth_service/terraform/api_gateway.tf
  src/campaign_service/terraform/api_gateway.tf
  src/email_service/terraform/api_gateway.tf
  src/file_service/terraform/api_gateway.tf
Labels: bug

#47 [SCRUM-109] Enable deletion protection and PITR based on the environment
  src/auth_service/terraform/dev.tfvars
  src/auth_service/terraform/dynamodb.tf
  src/auth_service/terraform/local-dev.tfvars
  src/auth_service/terraform/preview.tfvars
  src/auth_service/terraform/prod.tfvars
  src/auth_service/terraform/variables.tf
  src/campaign_service/terraform/dev.tfvars
  src/campaign_service/terraform/dynamodb.tf
  src/campaign_service/terraform/local-dev.tfvars
  src/campaign_service/terraform/preview.tfvars
  src/campaign_service/terraform/prod.tfvars
  src/campaign_service/terraform/variables.tf
  src/email_service/terraform/dev.tfvars
  src/email_service/terraform/dynamodb.tf
  src/email_service/terraform/local-dev.tfvars
  src/email_service/terraform/preview.tfvars
  src/email_service/terraform/prod.tfvars
  src/email_service/terraform/variables.tf
  src/file_service/terraform/dev.tfvars
  src/file_service/terraform/dynamodb.tf
  src/file_service/terraform/lambda.tf
  src/file_service/terraform/local-dev.tfvars
  src/file_service/terraform/preview.tfvars
  src/file_service/terraform/prod.tfvars
  src/file_service/terraform/variables.tf
Labels: enhancement

#48 [SCRUM-115] Fix `GET /files` 400 Error pagination bug - The provided starting key is outside query boundaries based on provided conditions
  src/file_service/list_files/lambda_function.py
  src/file_service/terraform/lambda.tf
Labels: bug

#49 [Release] v1.2.2
  src/auth_service/terraform/dev.tfvars
  src/auth_service/terraform/dynamodb.tf
  src/auth_service/terraform/local-dev.tfvars
  src/auth_service/terraform/preview.tfvars
  src/auth_service/terraform/prod.tfvars
  src/auth_service/terraform/variables.tf
  src/campaign_service/terraform/dev.tfvars
  src/campaign_service/terraform/dynamodb.tf
  src/campaign_service/terraform/local-dev.tfvars
  src/campaign_service/terraform/preview.tfvars
  src/campaign_service/terraform/prod.tfvars
  src/campaign_service/terraform/variables.tf
  src/email_service/terraform/dev.tfvars
  src/email_service/terraform/dynamodb.tf
  src/email_service/terraform/local-dev.tfvars
  src/email_service/terraform/preview.tfvars
  src/email_service/terraform/prod.tfvars
  src/email_service/terraform/variables.tf
  src/file_service/list_files/lambda_function.py
  src/file_service/terraform/dev.tfvars
  src/file_service/terraform/dynamodb.tf
  src/file_service/terraform/local-dev.tfvars
  src/file_service/terraform/preview.tfvars
  src/file_service/terraform/prod.tfvars
  src/file_service/terraform/variables.tf
Labels: Release

#50 [SCRUM-73] Send email API support reply-to, bcc, cc, sender local part
  src/email_service/send_email/email_util.py
  src/email_service/send_email/file_util.py
  src/email_service/send_email/lambda_function.py
  src/email_service/send_email/ses.py
  src/email_service/send_email/template_util.py
  src/email_service/terraform/lambda.tf
  src/email_service/validate_input/lambda_function.py
Labels: feature
